services:
  web:
    build:
      context: .
    container_name: sentiment_analysis_app
    restart: always
    volumes:
      - static-data:/vol/web
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    container_name: sa_postgres_db # sa: sentiment analysis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'localadmin', '-d', 'ml_db']
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 5s

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - web
    ports:
      #- 80:8000
      - 8001:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data:
